-- Esquema de base de datos para Viajes Aventura (Oracle)

-- Tabla de Usuarios
DECLARE
    cnt NUMBER;
BEGIN
    SELECT count(*) INTO cnt FROM user_tables WHERE table_name = 'USUARIOS';
    IF cnt = 0 THEN
        EXECUTE IMMEDIATE '
        CREATE TABLE usuarios (
            id NUMBER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
            nombre VARCHAR2(100) NOT NULL,
            email VARCHAR2(100) UNIQUE NOT NULL,
            password_hash VARCHAR2(255) NOT NULL,
            es_admin NUMBER(1,0) DEFAULT 0
        )';
    END IF;
END;
/

-- Tabla de Destinos
DECLARE
    cnt NUMBER;
BEGIN
    SELECT count(*) INTO cnt FROM user_tables WHERE table_name = 'DESTINOS';
    IF cnt = 0 THEN
        EXECUTE IMMEDIATE '
        CREATE TABLE destinos (
            id NUMBER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
            nombre VARCHAR2(100) NOT NULL,
            descripcion CLOB,
            actividades CLOB,
            costo_base NUMBER(10, 2) NOT NULL
        )';
    END IF;
END;
/

-- Tabla de Paquetes Turísticos
DECLARE
    cnt NUMBER;
BEGIN
    SELECT count(*) INTO cnt FROM user_tables WHERE table_name = 'PAQUETES';
    IF cnt = 0 THEN
        EXECUTE IMMEDIATE '
        CREATE TABLE paquetes (
            id NUMBER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
            nombre VARCHAR2(100) NOT NULL,
            fecha_inicio DATE NOT NULL,
            fecha_fin DATE NOT NULL,
            precio_total NUMBER(10, 2) NOT NULL
        )';
    END IF;
END;
/

-- Tabla Intermedia Paquetes - Destinos
DECLARE
    cnt NUMBER;
BEGIN
    SELECT count(*) INTO cnt FROM user_tables WHERE table_name = 'PAQUETE_DESTINOS';
    IF cnt = 0 THEN
        EXECUTE IMMEDIATE '
        CREATE TABLE paquete_destinos (
            paquete_id NUMBER REFERENCES paquetes(id) ON DELETE CASCADE,
            destino_id NUMBER REFERENCES destinos(id) ON DELETE CASCADE,
            PRIMARY KEY (paquete_id, destino_id)
        )';
    END IF;
END;
/

-- Tabla de Reservas
DECLARE
    cnt NUMBER;
BEGIN
    SELECT count(*) INTO cnt FROM user_tables WHERE table_name = 'RESERVAS';
    IF cnt = 0 THEN
        EXECUTE IMMEDIATE '
        CREATE TABLE reservas (
            id NUMBER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
            usuario_id NUMBER REFERENCES usuarios(id) ON DELETE CASCADE,
            paquete_id NUMBER REFERENCES paquetes(id) ON DELETE CASCADE,
            fecha_reserva TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
            estado VARCHAR2(50) DEFAULT ''confirmada''
        )';
    END IF;
END;
/
